language: node_js
node_js:
  - "stable"

notifications:
  email: false

addons:
  sauce_connect: true

env:
  global:
  - secure: "CheE1UdNMfCLItM4Ny0+TY8foEDsvqmMSewqk+LncNrDKL385mZ6NJnfbw97DGDpPvDPipelcymN1P96s/7VBvHR7leJF3P8Jn2EIOmlSA05OHRm2175D+VSPf7wvtHEPjucm5eigyoF3jDRQBBNFgeSOQyQaiNAShi2u3nwUKwbMKacYF5gD5clCASj5VX4buBdd1rFYFeL10JmkmaEAATGYs0Y33FjTLTO63jdHEPvUj6OrPY5jucasuZsbyeYTZLHWaPyuFVTVM2jOVmx0BFJLSgMSw+bOW3kZaERYF88qJz5zv1dZhu9l5eBEY5y03LX6Ophq17sB68JVK1mKZodoczfSn1dXzkCNf2hIwX7vVqaLqNarJQLD6KMt9FUnbevH98wwp4HLQvHVuNZc7XzjVGZY33SJXvGJV5gdx8vMqFib6dNapdZjk5eMMHxbGqj76Kmuud+Gz6pJBO3KCLXVPfUchRdN0XqmrM1OkAodrrnf/p7i//Sz7HGiUm51RX6z+nc9ylplSG1/5xPccoa/5je6qL8xmDKjjTrb+SMPcHLAQNvNTYMVQJ6YuquK46lNdMwyKLbczkWk2o3V1Mh7K7chXfks14UHRsJsb5/ZY8ibgFMOmijjb+aITy1Yvuw744Q+cy+ZcX2LfG7QmCJOIcs4BA/IvYl8nMqBLQ="
  - secure: "XQmDkLseBZWBhq7qteo8tcrZ+6SOQabfXN4eHGSxJrTnUddUkrfZ2vRjD42sR1odhO4xwaAV4duhw1GU0aCgApQ+JDmoeiNpLrUvviUgtS2ryeAsVzmmojN6wr5+8ZmTNfHf61yVXkRS1dsFZ0y8rmbTT7zV+rVYIMr5sY/JibrHuPn4p5ieHpzRqjlgqJVTa0evsCMn0Z/Zapy+fUlKlfwso3EaRlYOaZUA3pq1yDrzEvgp+YbsgkAIxa+PtbFmHbYhwgEpjJ9M2MJ+QPBf39aGVwy6UhDlOZKz90TfQwhtF/PEBI+YEYDe1+FfOLoXWHbNRn+tlCcvoY6s9lT0+mt0xk1eWkFiL1OK2CtCrtwwyV0kkW9I8Ra54w8LhL61dDWTjOJ9Kwy4+DKZG6vQplEBRtA8FPP8vIynLXUWOCI12WP2qovFMqEpnLB9s1Oj0j2M3TgcRvkHzSYVdfiLjN0xdY/RaH8ZYxCN5o4ZgSxPf+jUWfsjsRy8LVfiI8CyWIyuP94XBECc/6UFAJzlUTf4pUKXD0Autqn4KQSWj4jVqIkMwlZFfRbamPvfIBIHw08lgE2wSQB0SERtfkWQtbNpG75bXpw9aXPpfl5yFhYVoNg6HX3HO+566cJ3j07VE5byn030VBg9CQ9eN0FLEFNEoKhLdfYrjxT5Q4woRwM="